blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/project-jade-garden/bouquet-ui/discussions
    about: Ask questions and discuss topics with other devlopers
